### ISSUE TITLE
Cannot be installed on Android 12 devices

### ISSUE THREAD

**Issue by tmk815** [plaidev/karte-android-sdk#16]
## P.S.
I forgot to assume that the minSdkVersion of the project is 14 or more and 30 or less. I'm sorry if the issue is not supported.

## Expected Behavior

Can be successfully installed on Android 12.

## Current Behavior

I can't install it on my Android 12 device.

## Possible Solution

Grant the exported attribute.

Reference:https://developer.android.com/about/versions/12/behavior-changes-12#exported

## Steps to Reproduce

1.Change compileSdkVersion and targetSdkVersion
```
compileSdkVersion("android-S")
targetSdkVersion("S")
```
2.Sync gradle
3.build and run
4.faild

## SDK Version

- core 2.12.2
- inappmessaging 2.10.0
- notifications 2.7.2
- variables 2.2.0
- visualtracking 2.4.0
## Android Version
Android12

## Build Environment

- Android Studio Version Android Studio Arctic Fox | 2020.3.1 Patch 2
- Gradle Version 6.8
- Android Gradle Plugin Version 4.0.2

## Context Details

https://developer.android.com/about/versions/12/behavior-changes-12#exported

This is a bug that accompanies the correction of the above Android 12 changes.

## Logs
```
Installation failed due to: 'Failed to commit install session 1102893501 with command cmd package install-commit 1102893501. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1102893501.tmp/base.apk (at Binary XML file line #204): io.karte.android.visualtracking.PairingActivity: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present'

```

**Comment by wasnot** [comment]
@tmk815 
Thank you for your report.

As you pointed out, we do not currently support operation on Android 12 and `targetSdkVersion 31`.
However, it is desirable that it be supported at the time of official release, so it was very helpful to receive feedback.

We will respond to this.
please wait a little bit.
Thank you.
